import { ignoreAutoI18n } from '@kapo/webpack-plugin-i18n-transformer/dist/utils'

export const precentField = [
  'clickRate',
  'naturalSessionsRate',
  'spendRate',
  'naturalOrdersRate',
  'adOrdersRate',
  'adConversion',
  'tConversion',
  'adSalesRate',
  'salesRate',
  'acos',
  'tacos',
  'aSoAS',
  'returnRate',
  'profitRate',
]

export const symbolField = [
  'spend',
  'cpc',
  'adSales',
  'sales',
  'cpo',
  'avgPrice',
]

export const precentDetailField = [
  'clickRate',
  'organicTrafficShare',
  'spendRate',
  'naturalOrderRate',
  'adUnitsRate',
  'adConversion',
  'tconversion',
  'adSalesRate',
  'salesRate',
  'acos',
  'gxb',
  'asos',
  'returnRate',
  'profitRate',
]

export const symbolDetailField = [
  'spend',
  'cpc',
  'adSales',
  'sales',
  'cpo',
  'avgPrice',
]

export const chartSelected = {
  [ignoreAutoI18n('广告曝光量')]: true,
  [ignoreAutoI18n('广告点击量')]: true,
  [ignoreAutoI18n('广告点击率（CTR）')]: true,
  [ignoreAutoI18n('Sessions-PC')]: true,
  [ignoreAutoI18n('Sessions-Browser')]: false,
  [ignoreAutoI18n('Sessions')]: false,
  [ignoreAutoI18n('自然流量')]: false,
  [ignoreAutoI18n('自然流量占比')]: false,
  [ignoreAutoI18n('PV')]: false,
  [ignoreAutoI18n('广告花费')]: false,
  [ignoreAutoI18n('广告花费占比')]: false,
  [ignoreAutoI18n('CPC')]: false,
  [ignoreAutoI18n('总订单量')]: false,
  [ignoreAutoI18n('广告订单量')]: false,
  [ignoreAutoI18n('实际广告订单量')]: false,
  [ignoreAutoI18n('自然订单')]: false,
  [ignoreAutoI18n('自然订单占比')]: false,
  [ignoreAutoI18n('广告销量')]: false,
  [ignoreAutoI18n('实际广告销量')]: false,
  [ignoreAutoI18n('总销量')]: false,
  [ignoreAutoI18n('广告销量占比')]: false,
  [ignoreAutoI18n('广告转化率（CVR）')]: false,
  [ignoreAutoI18n('总转化率')]: false,
  [ignoreAutoI18n('广告销售额')]: false,
  [ignoreAutoI18n('实际广告销售额')]: false,
  [ignoreAutoI18n('广告销售额占比')]: false,
  [ignoreAutoI18n('总销售额')]: false,
  [ignoreAutoI18n('总销售额占比')]: false,
  [ignoreAutoI18n('ACOS')]: false,
  [ignoreAutoI18n('ROAS')]: false,
  [ignoreAutoI18n('广销比（TACOS）')]: false,
  [ignoreAutoI18n('ASoAS')]: false,
  [ignoreAutoI18n('CPO')]: false,
  [ignoreAutoI18n('平均价格')]: false,
  [ignoreAutoI18n('退货率')]: false,
  [ignoreAutoI18n('FBA可售')]: false,
  [ignoreAutoI18n('周转天数')]: false,
  [ignoreAutoI18n('利润率')]: false,
}

export const lineChartOption = [
  { name: '广告曝光量', yAxisfield: 'impressionsList' },
  { name: '广告点击量', yAxisfield: 'clickList' },
  { name: '广告点击率（CTR）', yAxisfield: 'clickRateList' },
  { name: 'Sessions-PC', yAxisfield: 'appSessionList' },
  { name: 'Sessions-Browser', yAxisfield: 'browserSessionList' },
  { name: 'Sessions', yAxisfield: 'sessionList' },
  { name: '自然流量', yAxisfield: 'organicTrafficList' },
  { name: '自然流量占比', yAxisfield: 'organicTrafficShareList' },
  { name: 'PV', yAxisfield: 'pageViewList' },
  { name: '广告花费', yAxisfield: 'spendList' },
  { name: '广告花费占比', yAxisfield: 'spendRateList' },
  { name: 'CPC', yAxisfield: 'cpcList' },
  { name: '总订单量', yAxisfield: 'itemsList' },
  { name: '广告订单量', yAxisfield: 'adOrderList' },
  { name: '实际广告订单量', yAxisfield: 'actualOrdersList' },
  { name: '自然订单', yAxisfield: 'naturalOrderList' },
  { name: '自然订单占比', yAxisfield: 'naturalOrderRateList' },
  { name: '广告销量', yAxisfield: 'adUnitsList' },
  { name: '实际广告销量', yAxisfield: 'actualSalesVolumeList' },
  { name: '总销量', yAxisfield: 'ordersList' },
  { name: '广告销量占比', yAxisfield: 'adUnitsRateList' },
  { name: '广告转化率（CVR）', yAxisfield: 'adConversionList' },
  { name: '总转化率', yAxisfield: 'tconversionList' },
  { name: '广告销售额', yAxisfield: 'adSalesList' },
  { name: '广告销售额占比', yAxisfield: 'adSalesRateList' },
  { name: '总销售额', yAxisfield: 'salesList' },
  { name: '实际广告销售额', yAxisfield: 'actualSalesList' },
  { name: '总销售额占比', yAxisfield: 'salesRateList' },
  { name: 'ACOS', yAxisfield: 'acosList' },
  { name: 'ROAS', yAxisfield: 'roasList' },
  { name: '广销比（TACOS）', yAxisfield: 'gxbList' },
  { name: 'ASoAS', yAxisfield: 'asoAsList' },
  { name: 'CPO', yAxisfield: 'cpoList' },
  { name: '平均价格', yAxisfield: 'avgPriceList' },
  { name: '退货率', yAxisfield: 'returnRateList' },
  { name: 'FBA可售', yAxisfield: 'inventoryList' },
  { name: '周转天数', yAxisfield: 'zhtList' },
  { name: '利润率', yAxisfield: 'profitRateList' },
]

